### ISSUE TITLE
Issue #2 - Print "Hello World" in Perl.

### ISSUE THREAD

**Issue by ShreyasheeS** [ShreyasheeS/Hacktoberfest#3]
Write a program in **Perl** that prints "Hello World".
You'll need to open a command-line terminal. On OS X, use the finder to launch Applications -> Utilities -> Terminal. On Ubuntu, this is Applications -> Accessories -> Terminal. On Windows, click Start -> Run, type cmd into the prompt, and click OK.

**Comment by amitsin6h** [comment]
let me take this as my first contribution here
